name: 'My Custom PowerShell Action'
description: 'A custom GitHub action written in PowerShell'
inputs:
  CONTENT:
    description: 'This is the content to be included in the slack post'
    required: true
  SLACKURL:
    description: 'This is full url for posting to slack'
    required: true
  TESTMODE:
    description: 'if set this will just output the json message rather than post'
    required: false
  GH_TOKEN:
    description: 'used to get information about the github action using this'
  GITHUB_CONTEXT:
    description: 'used to get information about the github action using this'
  RUNNER:
    description: 'info about the runner'
runs:
  # using: 'docker'
  # image: 'Dockerfile'
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: secrets
      shell: bash
      run: |
        echo "${{ inputs.SLACKURL }}"

    - name: step 1
      shell: pash
      run: |
        echo "TEST: ${{ inputs.SLACKURL }}"
        echo "TEST2: $env:thesecret"
        echo "TEST3: $env:thesecret2"
        # ./main.ps1
