name: 'My Custom PowerShell Action'
description: 'A custom GitHub action written in PowerShell'
inputs:
  exampleInput:
    description: 'An example input'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
