name: 'My Custom PowerShell Action'
description: 'A custom GitHub action written in PowerShell'
inputs:
  CONTENT:
    description: 'This is the content to be included in the slack post'
    required: true
  SLACKURL:
    description: 'This is full url for posting to slack'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
