name: Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run custom PowerShell action
        uses: .
        with:
          content: 'Test Content - I will need to do a test where this is really big'
          slackurl: "test_url"
          testmode: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          RUNNER: ${{ runner.environment }}
  