name: Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      - name: set var
        shell: bash
        id: secret1
        env:
          SECRET: "test_secret"
        run: |
          echo "::add-mask::$SECRET"
          echo "thesecret=$SECRET" >> "$GITHUB_ENV"

      # - name: test output
      #   shell: bash
      #   env:
      #     TEST: ${{ steps.secret1.output.thesecret }}
      #   run: |
      #     echo "test: $thesecret"
      #     echo "test: $thesecret2"
      #     echo "secret is: ${{ steps.secret1.output.thesecret }}"
      #     echo "secret2 is: ${{ steps.secret1.output.thesecret2 }}"
      #     echo "secret set as env is: $TEST"

      - name: Run custom PowerShell action
        uses: air-ltd/slackpost@main
        with:
          CONTENT: 'Test Content - I will need to do a test where this is really big'
          SLACKURL: $thesecret
          TESTMODE: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          RUNNER: ${{ runner.environment }}
  