name: Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      - name: set var
        shell: bash
        id: secret1
        env:
          SECRET: "test_secret"
        run: |
          echo "::add-mask::$SECRET"
          echo "slack_url=$SECRET" >> "$GITHUB_ENV"
          echo "message=$(printf 'a%.0s' {1..23})" >> "$GITHUB_ENV"
          echo "this is a file test" > log.txt
          echo "this is a file test - line 2" >> log.txt
          echo "msg_file=$(readlink -f log.txt)" >> "$GITHUB_ENV"

      - name: Test Env
        shell: pwsh
        run: |
          echo "Env File: $($env:msg_file)"

      - name: Run custom PowerShell action
        uses: air-ltd/slackpost@4-add-support-for-passing-file-with-content-for-the-slack-post
        with:
          CONTENT_FILE: ${{ env.msg_file }}
          CONTENT: ${{ env.message }}
          SLACKURL: ${{ env.slack_url }}
          TESTMODE: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          RUNNER: ${{ runner.environment }}
  
      - name: Run custom PowerShell action 2
        uses: air-ltd/slackpost@4-add-support-for-passing-file-with-content-for-the-slack-post
        with:
          CONTENT: ${{ env.message }}
          SLACKURL: ${{ env.slack_url }}
          TESTMODE: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          RUNNER: ${{ runner.environment }}
  
      - name: Run custom PowerShell action 3
        uses: air-ltd/slackpost@4-add-support-for-passing-file-with-content-for-the-slack-post
        with:
          CONTENT_FILE: ${{ env.msg_file }}
          SLACKURL: ${{ env.slack_url }}
          TESTMODE: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          RUNNER: ${{ runner.environment }}
  