name: Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      - name: set var
        shell: bash
        id: secret1
        env:
          SECRET: "test_secret"
        run: |
          echo "::add-mask::$SECRET"
          echo "thesecret=$SECRET" >> "$GITHUB_ENV"
          echo "message=$(printf 'a%.0s' {1..3010})" >> "$GITHUB_ENV"

      - name: Run custom PowerShell action
        uses: air-ltd/slackpost@main
        with:
          CONTENT: $message
          SLACKURL: $thesecret
          # TESTMODE: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          RUNNER: ${{ runner.environment }}
  