name: Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      - name: set var
        id: secret
        env:
          SECRET: "test_secret"
        run:
          echo "::add-mask::$SECRET"
          echo "the-secret=$SECRET" >> "$GETHUB_OUTPUT"


      - name: Run custom PowerShell action
        uses: air-ltd/slackpost@main
        with:
          CONTENT: 'Test Content - I will need to do a test where this is really big'
          SLACKURL: ${{ steps.secret.output.the-secret }}
          TESTMODE: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          RUNNER: ${{ runner.environment }}
  